### ISSUE TITLE
weird "Nope" box on homepage

### ISSUE THREAD

**Issue by dauidus** [dauidus/Github-Workshop-sec-3#4]
I don't know where this came from, but its messing with the whole chill vibe of our site.  Needs to go!

**Comment by dani5612** [comment]
just fixed it all by myself B)

**Comment by dauidus** [comment]
got rid of second image with weird spacing and Nope alt text

**Comment by dauidus** [comment]
This bug isn't actually fixed - we still got a Nope comment with an empty image.

**Comment by dani5612** [comment]
got rid of the button

**Comment by dauidus** [comment]
actually fixed it... GOSH!

**Comment by dani5612** [comment]
Dauidus is stealing the credit for my work smh
